feat: add authentication on backend with passport for social login
gdsc-ssu/sasil-server pull request #10
Opened 2022-03-18 08:31 UTC by kanghyun98

## Issue
#5 소셜로그인 기능 구현 (with passport)

## Description
사용자 인증 미들웨어 라이브러리 `passport`를 이용하여 구글, 카카오, 애플(아직 진행하지 않음)의 백엔드 단에서 인증 로직을 구현

### Strategy
`src/auth/strategy.ts` 파일에 각각의 로그인 전략이 위치하며, 구글과 카카오의 경우 사실상 clientID, clientSecret, callbackURL(redirectURI)을 제외하고는 모두 동일한 방식이다.
별도의 창에서 소셜로그인 성공 시(해당 기능 다음 이슈에서 진행), 유저의 정보를 `email`, `loginType`을 식별자로 이용해 가져오고, 존재하지 않을 경우 자동 회원가입 처리하여 정보를 받아온다. (랜덤 프로필 사진, 닉네임 다음 이슈에서 진행)
이후 `done(null, userData)` 함수로 해당 데이터를 전달하는데, 간략히 이야기하자면 `passport.authenticate`의 두번째 인자로 오는 콜백함수의 인자로 전달된다. (다음 이슈에서 진행)

### `serializeUser()`, `deserializeUser()` 부분
- `serializeUser`: 선택한 `user.id`값을 직렬화를 통해 세션에 저장될 수 있는 포맷으로 바꾼 뒤 `req.session`(세션) 객체에 저장), 로그인시에 딱 한번 실행한다.
- `deserializeUser`: `req.session`(세션)에 저장된 `id`를 통해 메모리에 저장된 `id`를 찾아서 가져오고, 해당 `id`와 연결된 `user.id`를 이용해 user 정보 불러와 반환한다. 조회된 결과값은 `req.user`에 담김, 페이지를 이동할때마다 (`passport.session()`이 실행될때마다) 호출한다.

추가적으로 `serializeUser()`의 콜백함수의 인자 중 타입 이슈가 있었는데, `user`의 타입이 `Express.User`로 요구되어 맞춰줄 수 없는 상황이었다.
광서의 조언과 구글링을 통해 `typeRoots` 라는 것을 알게 되었고, 이를 적용하여 문제를 해결함 (`src/types/index.d.ts`, `tsconfig.json, package.json` 변경 부분 참고) ++ `tsnode`의 경우 `typeRoots`를 인식하지 못해 `scripts.dev`에 `--files` 옵션을 추가함
-> 혹시 내가 잘못 설정한게 있다면 알려주라!

### 추후 보강할 내용 (#7 혹은 추가 이슈 생성 후 진행)
- app.ts에 설정 추가
- 프로필, 닉네임 랜덤 생성
- apple login
- routes

가장 큰 문제는 프론트에서 아직 돌려보질 못해서 어떤 문제가 생길지 모른다는건데, 다음 이슈 진행할 때 front를 초초초간단하게 만들어서 테스트까지 해볼 예정!

## Check List
- [x] PR 제목을 commit 규칙에 맞게 작성
- [x] WIP를 붙여야 하는 상황인지 확인
- [x] label 설정
- [x] 작업한 사람 모두를 Assign
- [x] Code Review 요청

2022-03-18 08:37 UTC, ballsona submitted a review, later dismissed
Fast.. and .. Great...

2022-03-18 13:44 UTC, aube-dev requested changes

2022-03-18 13:44 UTC, aube-dev commented on src/database/controllers/user.ts
> +export const getUserDataById = async (id: number) => {
사소한 생각이긴 한데 그냥 `getUserById`라고 해도 괜찮지... 않으려나?

2022-03-18 13:44 UTC, aube-dev commented on src/database/controllers/user.ts
> +export const getUserDataByEmailAndType = async (
조금 더 심플한 이름이 있으면 좋을 것 같아! `getUserByLoginInfo` 정도...?

2022-03-18 13:44 UTC, aube-dev commented on src/database/controllers/user.ts
> +type LoginTypes = 'kakao' | 'google' | 'apple';
혹시 그때 유니온 타입 vs enum 얘기 때문에 유니온 타입으로 한 거야? 개인 의견이긴 한데 `const enum`으로 해도 되지 않을까 싶어!

2022-03-18 13:44 UTC, aube-dev commented on src/database/controllers/user.ts
> +type LoginTypes = 'kakao' | 'google' | 'apple';
그리고 이 login type 정의는 user entity 쪽에서 하고 여기에 import해오면 어떨까? login type 정의는 user entity쪽에서도 쓰이기도 하고, 애초에 로직보다는 column의 타입 정의니까

2022-03-18 13:44 UTC, aube-dev commented on src/database/controllers/user.ts
> +    profile: 'test', // TODO: random 생성
생각해보니 랜덤으로 어떻게 생성할지 로직을 정해야 되네... 이거 다음 스프린트 작업으로 이슈 만들어줄 수 있을까?

2022-03-18 13:44 UTC, aube-dev commented on src/constants/index.ts
> +  redirectURIApple: 'http://localhost:3000/auth/apple/callback',
```suggestion
  redirectURI: {
    google: 'http://localhost:3000/auth/google/callback',
    kakao: 'http://localhost:3000/auth/kakao/callback',
    apple: 'http://localhost:3000/auth/apple/callback',
  }
```
이렇게 바꾸면 어떨까!

2022-03-18 13:44 UTC, aube-dev commented on src/constants/index.ts
> +  redirectURIApple: 'http://localhost:3000/auth/apple/callback',
그리고 `as const` 붙여서 혹시라도 값이 변경되는 걸 막으면 어떨까?
```typescript
export const DEV_SETTING = {
  // ...
} as const;
```

2022-03-18 13:49 UTC, aube-dev commented on src/database/controllers/user.ts
> +    profile: 'test', // TODO: random 생성
#7 에 추가하거나 새로 이슈 만들겠다고 써놓은 것 중에 애플 로그인만 빼면 #7 에 추가해도 될 것 같아! 애플 로그인은 내 생각에 이 PR에서 계속 진행하고, 그동안 이 PR은 WIP로 놓는 게 나을 것 같아 (내가 WIP 봇을 삭제했는데 깃허브에 PR을 Draft로 변환하는 기능이 있어서 이거 쓰면 WIP랑 똑같으니까 그렇게 하면 될 것 같아)

2022-03-18 13:53 UTC, kanghyun98 commented on src/database/controllers/user.ts
> +export const getUserDataByEmailAndType = async (
오오 괜찮은 네이밍 추천 감사함다ㅠㅠ

2022-03-18 14:40 UTC, kanghyun98 commented on src/database/controllers/user.ts
> +type LoginTypes = 'kakao' | 'google' | 'apple';
user entity에서도 enum으로 타입 정의해주니깐 중복성 제거 측면에서 일리가 있다!

근데 진행해봤는데 문제가 있어!
1. `const enum`을 user entitiy 정의부분에서 사용하면 아래와 같은 오류가 뜸 (일반 `enum`으로 정의해주면 문제 없긴해.. 공식문서에도 그냥 `enum`으로 정의해서 사용하는 방식만 나와있네;)
<img width="483" alt="image" src="https://user-images.githubusercontent.com/70627979/159022318-8a6deac3-910f-41ad-96f6-353d57bfd658.png">

2. eslint [no-shadow](https://eslint.org/docs/rules/no-shadow) 문제
이건 `const enum` 문제가 아니긴한데, 그냥 갑자기 뜨길래 올려봤어! 그냥 `enum`으로 해도 똑같이 뜬다!
찾아보니깐 나름 유명한거더라구, 여기 [stackoverflow](https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope)에도 나와있고 다른 곳에서도 eslint에서 아래와 같이 설정해주면 해결된다함! 혹시 이거에 대해 더 좋은 해결방안이 있으면 알려주라!
```
{
  "rules": {
      "no-shadow": "off",
      "@typescript-eslint/no-shadow": ["error"]
  },
}
```

2022-03-18 14:58 UTC, kanghyun98 commented on src/database/controllers/user.ts
> +type LoginTypes = 'kakao' | 'google' | 'apple';
그래서 내가 생각해본 해결방법은 user entity 에서 `LoginTypes`를 `union` 방식으로 선언하고, 너가 말했듯이 import 하는 방식을 사용해볼까해! 어때??

```
// entity/user.ts
export type LoginTypes = 'apple' | 'google' | 'kakao';

...
@Column({ type: 'enum', enum: ['kakao', 'google', 'apple'] })
  login_type!: LoginTypes;

```

2022-03-18 15:08 UTC, kanghyun98 commented on src/database/controllers/user.ts
> +    profile: 'test', // TODO: random 생성
1. 오키! 로그인 API 이슈 TODO에 추가해놓을게 (다른것들도!)
2. 확인! 근데 WIP 모드로 냅두면, 로그인API를 위한 브랜치는 현재 브랜치를 기점으로 파고 진행한 다음, 나중에 현재 브랜치에서 애플로그인 로직을 구현하면 에픽에 squash하고, 로그인API에서 이거를 rebase(혹은 merge)하면 되는건가?

2022-03-18 15:10 UTC, kanghyun98 commented on src/constants/index.ts
> +  redirectURIApple: 'http://localhost:3000/auth/apple/callback',
와우... 진짜 생각도 못했넼ㅋㅋ constants에서 저 부분 정말 맘에 안들었었는데,,
한 수 배웁니다ㅎ

`as const`라는걸 잘 몰랐는데, 이참에 공부해봐야겠다! 추천 고마워!

2022-03-19 06:16 UTC, aube-dev commented on src/database/controllers/user.ts
> +type LoginTypes = 'kakao' | 'google' | 'apple';
1. 저 문제가 왜 일어나는지 정확히는 모르겠지만, 아마 `const enum`은 `enum`과 달리 실제로 js로 컴파일될 때는 없어지기 때문에 그런 게 아닐까 싶네! 이거랑은 별개로 [이런 글](https://www.kabuku.co.jp/developers/good-bye-typescript-enum)을 추가적으로 보니 그냥 `const enum`도 안 쓰는 게 낫네... [이 글](https://ajdkfl6445.gitbook.io/study/typescript/enum-type-union-type)에서 한 방식처럼 union type을 적극적으로 활용하는 게 나을 것 같아
2. no-shadow 문제는 나도 겪었어서 안그래도 추가해야겠다 싶었어 ㅋㅋㅋㅋㅋ 솔루션챌린지할 때는 이렇게 설정했어
```json
{
  "rules": {
    "no-unused-vars": 0,
    "@typescript-eslint/no-unused-vars": ["warn"],
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": ["error"],
  }
}
```

2022-03-19 06:18 UTC, aube-dev commented on src/database/controllers/user.ts
> +    profile: 'test', // TODO: random 생성
2. 이거 보고 다시 생각해 보니 다른 작업에 이 작업이 필요하니까 이건 먼저 완료하고 애플 로그인만 새로 태스크를 만드는 게 낫겠네...

2022-03-19 06:23 UTC, aube-dev commented on src/database/controllers/user.ts
> +    profile: 'test', // TODO: random 생성
2. 그렇게 하면 될 것 같아!

2022-03-20 14:12 UTC, aube-dev approved these changes
LGTM!!

2022-03-20 14:19 UTC, merged