chore: fix settings about .dummy.env and .vscode
gdsc-ssu/sasil-server pull request #4
Opened 2022-03-14 15:52 UTC by kanghyun98

## Issue
none

## Description
.dummy.env 파일 내부 수정 및 .vscode 관련 설정들 front와 통일

## Check List
- [x] PR 제목을 commit 규칙에 맞게 작성
- [x] WIP를 붙여야 하는 상황인지 확인
- [x] label 설정
- [x] 작업한 사람 모두를 Assign
- [x] Code Review 요청

2022-03-14 15:54 UTC, aube-dev requested changes

2022-03-14 15:54 UTC, aube-dev commented on .vscode/settings.json
> +  ],
이건 monorepo 설정이라 서버에서는 필요가 없어요!

2022-03-14 15:56 UTC, kanghyun98 commented on .vscode/settings.json
> +  ],
반영할게여!

2022-03-14 16:00 UTC, aube-dev approved these changes, later dismissed
LGTM 👍

2022-03-15 16:55 UTC, aube-dev approved these changes, later dismissed
LGTM 👍

2022-03-15 16:55 UTC, aube-dev commented on src/constants/index.ts
> +export const DB_DATABASE = 'sasil';
이 방식도 좋고! 이런 느낌도 좋을 것 같아
```typescript
export const DEV_SETTING = {
  port: '3065',
  db: {
    host: 'localhost',
    port: '3306',
    database: 'sasil-dev'
  }
}
```
이렇게 하면 정보들에 이름을 붙여서 좀 더 직관적으로 관리할 수 있고 쓸 때도 `DEV_SETTING.db.port` 이런 식으로 좀 더 편하게 쓸 수 있는 것 같아! 일일이 `import {DEV_PORT, DEV_DB_HOST, DEV_DB_PORT, DEV_DB_DATABASE} from '@constants/'`처럼 안 써도 되니까 그것도 좋은 것 같고...?

2022-03-15 16:55 UTC, aube-dev commented on src/database/config/ormconfig.ts
> +} from '@/constants/index';
위 코멘트 참고!

2022-03-15 17:01 UTC, ballsona approved these changes, later dismissed
LGTM !!!

2022-03-15 17:02 UTC, aube-dev commented on src/constants/index.ts
> +export const DB_DATABASE = 'sasil';
아니면 조금 다른 시각으로 좀 더 카테고리에 집중해서
```typescript
export const DB = {
  dev: {
    host: 'localhost',
    port: '3306',
    database: 'sasil-dev'
  },
  production: {
    host: 'localhost',
    port: '3306',
    database: 'sasil'
  }
};

export const PORT = {
  dev: '3065',
  production: ''
 };
 ```
 이런 느낌도 고민되네! 근데 우선은 지금 상황에서는 dev/production으로 나누는 게 좀 더 중심인 것 같아서 이거는 나중에 상수 많아지면 고려해보는 게 나을 것 같아

2022-03-15 17:02 UTC, kanghyun98 commented on src/constants/index.ts
> +export const DB_DATABASE = 'sasil';
처음에 dev와 prod 모드의 구분 목적으로만 보고 객체를 이용한 방식이 별로일거라 생각해서 위 방식으로 구현했는데, 기능 단위로 더 나눈거 보니깐 객체 방식이 더 좋아보이네..! 반영할게유ㅎ

2022-03-16 04:37 UTC, aube-dev approved these changes
완벽해요 👍

2022-03-16 04:38 UTC, ballsona approved these changes
👍👍👍👍

2022-03-16 04:40 UTC, merged